<?xml version="1.0"?>
<robot name="robotsim2" xmlns:xacro="http://www.ros.org/wiki/xacro">

    
    <xacro:property name="base_width" value="0.3"/>
    <xacro:property name="base_length" value="0.3"/>
    <xacro:property name="base_height" value="0.1"/>
    <xacro:property name="wheel_radius" value="0.05"/>
    <xacro:property name="wheel_width" value="0.04"/>

    
    <xacro:macro name="wheel" params="prefix x y">
        <link name="${prefix}_wheel">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
                <material name="black">
                    <color rgba="0 0 0 1"/>
                </material>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
            </collision>
            <inertial>
                <mass value="0.25"/>
                <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
            </inertial>
        </link>

        <joint name="${prefix}_wheel_joint" type="continuous">
            <parent link="base_link"/>
            <child link="${prefix}_wheel"/>
            <origin xyz="${x} ${y} -0.04" rpy="${pi/2} 0 0"/>
            <axis xyz="0 0 1"/>
        </joint>

        <transmission name="${prefix}_wheel_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${prefix}_wheel_joint">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            </joint>
            <actuator name="${prefix}_wheel_motor">
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>
    </xacro:macro>

    
    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <material name="white">
                <color rgba="1 1 1 1"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="4"/>
            <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
        </inertial>
    </link>

    
    <xacro:wheel prefix="front_right" x="${base_length/2}" y="${-base_width/2 - wheel_width/2}"/>
    <xacro:wheel prefix="front_left" x="${base_length/2}" y="${base_width/2 + wheel_width/2}"/>
    <xacro:wheel prefix="rear_right" x="${-base_length/2}" y="${-base_width/2 - wheel_width/2}"/>
    <xacro:wheel prefix="rear_left" x="${-base_length/2}" y="${base_width/2 + wheel_width/2}"/>




</robot>